package com.center.buuluu.dao.mapper;

import java.util.Map;

import org.springframework.stereotype.Component;

import com.center.buuluu.annotation.MyBatisRepository;
import com.center.buuluu.model.AppUserSession;

@Component
@MyBatisRepository
public interface AppUserSessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_session
     *
     * @mbggenerated Thu Aug 20 14:57:06 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_session
     *
     * @mbggenerated Thu Aug 20 14:57:06 CST 2015
     */
    int insert(AppUserSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_session
     *
     * @mbggenerated Thu Aug 20 14:57:06 CST 2015
     */
    int insertSelective(AppUserSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_session
     *
     * @mbggenerated Thu Aug 20 14:57:06 CST 2015
     */
    AppUserSession selectByPrimaryKey(long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_session
     *
     * @mbggenerated Thu Aug 20 14:57:06 CST 2015
     */
    int updateByPrimaryKeySelective(AppUserSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_session
     *
     * @mbggenerated Thu Aug 20 14:57:06 CST 2015
     */
    int updateByPrimaryKey(AppUserSession record);
    
    AppUserSession getUserSessionByUserId(String userId);

	AppUserSession checkUserSession(Map<String, String> map);

	int updateUserSession(Map<String, String> map);

}