package com.center.buuluu.dao.mapper;

import org.springframework.stereotype.Component;

import com.center.buuluu.annotation.MyBatisRepository;
import com.center.buuluu.model.AppVistorUser;

@Component
@MyBatisRepository
public interface AppVistorUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vistor_user
     *
     * @mbggenerated Thu Aug 20 17:03:26 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vistor_user
     *
     * @mbggenerated Thu Aug 20 17:03:26 CST 2015
     */
    int insert(AppVistorUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vistor_user
     *
     * @mbggenerated Thu Aug 20 17:03:26 CST 2015
     */
    int insertSelective(AppVistorUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vistor_user
     *
     * @mbggenerated Thu Aug 20 17:03:26 CST 2015
     */
    AppVistorUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vistor_user
     *
     * @mbggenerated Thu Aug 20 17:03:26 CST 2015
     */
    int updateByPrimaryKeySelective(AppVistorUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vistor_user
     *
     * @mbggenerated Thu Aug 20 17:03:26 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(AppVistorUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_vistor_user
     *
     * @mbggenerated Thu Aug 20 17:03:26 CST 2015
     */

	AppVistorUser getUserById(String userId);
}